name = "moddtted"
author = "oodo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91b7527473ba32dd09642d552bae6696059c8de4a976a43a78453d909a05b9c0"

[versions]
fabric = "0.16.2"
minecraft = "1.21.1"
